[build]
  base = "."
  command = "cd client && npm install && node build-debug.js"
  publish = "client/build"
  environment = { NODE_VERSION = "16", NETLIFY_USE_YARN = "false", DEBUG = "true" }

[[plugins]]
  package = "./netlify-build-plugin.js"

[functions]
  directory = "server"
  node_bundler = "esbuild"

[[functions]]
  name = "server"
  external_node_modules = ["sequelize", "sqlite3", "pg", "pg-hstore", "mysql2"]

[[functions]]
  name = "uploads"
  path = "/uploads/*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
