[phases.install]
cmds = [
  "npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "echo '🏗️ Building React client...'",
  "cd client && CI=false npm run build",
  "echo '✅ Client build completed'",
  "ls -la client/build/",
  "node railway-build-verification.js"
]

[phases.start]
cmd = "node server/index.js"
