[phases.install]
cmds = [
  "npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "echo '🚫 CACHE DISABLED: Force fresh build'",
  "cd client && npm cache clean --force",
  "cd client && CI=false npm run build --no-cache",
  "echo '✅ Cache-disabled build completed'"
]

[phases.start]
cmd = "node server/index.js"
