[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
projectPaths = ["client"]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
