[phases.install]
cmds = [
  "npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "node railway-build-verification.js"
]

[phases.start]
cmd = "node server/index.js"
