services:
  # Web service for the full-stack application
  - type: web
    name: analytical-lab
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    numInstances: 1
    startCommand: bash render-setup.sh && node server/index.js
    disk:
      name: uploads
      mountPath: /var/data
      sizeGB: 1
    buildFilter:
      paths:
        - package.json
        - server/**
        - client/**
    buildEnvironment:
      # Required for building sqlite3 from source
      - name: PYTHON
        value: python3
      - name: NODE_SQLITE3_BINARY_HOST_MIRROR
        value: https://github.com/TryGhost/node-sqlite3/releases/download
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: analytical-lab-db
          property: connectionString
        # This will be automatically set by Render when the PostgreSQL database is provisioned
        # If you're not using a Render PostgreSQL database, you'll need to set this manually
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
        # Set this to your admin email during deployment
      - key: ADMIN_PASSWORD
        sync: false
        # Set this to a secure password during deployment
      - key: ALLOWED_ORIGINS
        sync: false
        # Set this to your frontend URL during deployment

# Database service
databases:
  - name: analytical-lab-db
    plan: free
    databaseName: analytical_lab_db
    user: analytical_lab_user
