name: Deploy to Render

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}  # You'll need to add this in GitHub secrets
          api-key: ${{ secrets.RENDER_API_KEY }}  # You'll need to add this in GitHub secrets
